cluster_username="apikey" # default username for any OCP cluster
cluster_password="8i7XdezLsEvHjWanA8DG4zn7-XJWYjuomZ6JouKHaQsF"  ## IBM Cloud account API Key
server_url="https://c102-e.eu-de.containers.cloud.ibm.com:31668" ## OCP cluster URL
namespace="cp4i-apic" # namespace name
cluster_type = "openshift"
git_org="vijayksorg" # github org name
git_repo="gitops-test-cp4i-all-4" # github repo name which is not existing 
git_username="vijayks" # github user name
git_token="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" # Personal Access Token for our github repo.
cp_entitlement_key="eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE1NzE4MzA0NjgsImp0aSI6ImNiMGFlZTNkZWE1NDQ4YmRiMmMwMjZjMDA0MjZlODhkIn0.Af46a1AiGZ4HaxvtVoc9rGvZ2xaSh2m1yqkzy2deJaA" 