cluster_username="apikey" # default username for any OCP cluster
cluster_password="rdiUJWdRd0sxK4Semz60uAZSZO5rrFwE-xukCG2YvIT7"  ## IBM Cloud account API Key
server_url="https://c116-e.us-south.containers.cloud.ibm.com:31720" ## OCP cluster URL
namespace="apic" # namespace name
cluster_type = "openshift"
git_org="divyakamathorg" # github org name
git_repo="gitops-test-cp4i-instance" # github repo name which is not existing 
git_username="diimallya" # github user name
git_token="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" # Personal Access Token for our github repo.
cp_entitlement_key="eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJJQk0gTWFya2V0cGxhY2UiLCJpYXQiOjE1NzE4MzA0NjgsImp0aSI6ImNiMGFlZTNkZWE1NDQ4YmRiMmMwMjZjMDA0MjZlODhkIn0.Af46a1AiGZ4HaxvtVoc9rGvZ2xaSh2m1yqkzy2deJaA" 